<?php

namespace common\models\card;

use common\models\enterprise\EnterpriseUser;
use common\program\Entrance;
use crazyfd\qiniu\Qiniu;
use Yii;

/**
 * This is the model class for table "business_cards".
 *
 * @property int $id
 * @property int $enterprise_id 企业id
 * @property int $integral 积分
 * @property int $popularity 人气
 * @property int $reliable 靠谱
 * @property int $share 转发
 * @property int $follow 被保存数量
 * @property int $status 状态
 * @property string $portrait 头像
 * @property string $userid 用户id
 * @property string $corpid 微信企业id
 * @property string $openid openid
 * @property string $name 名称
 * @property string $tel 电话
 * @property string $autograph 签名
 * @property string $copy_phone 保存电话数量
 * @property string $copy_email 保存邮箱数量
 * @property string $copy_wechat 保存微信数量
 * @property string $see_dynamic 查看朋友圈
 * @property string $see_website 查看网站
 * @property string $see_pro 查看商品
 * @property string $call_phone 呼叫手机
 * @property string $play_voice 播放语音
 * @property string $voice 录音地址
 * @property string $autograph_fabulous 签名点赞
 * @property string $information_num 咨询人数
 * @property string $inactive_num 待跟进
 * @property string $active_num 跟进中
 * @property string $invitations_num 已邀约
 * @property string $deal_num 已成交
 * @property string $deal_order 成交订单数
 * @property string $deal_amount 成交金额
 * @property string $wechat 维信
 * @property string $position 职位
 * @property string $company 公司
 * @property string $address 地址
 * @property string $email 邮件
 * @property string $details 详情
 * @property int $created_at 创建时间
 * @property int $updated_at 更新时间
 */

class BusinessCards extends \yii\db\ActiveRecord{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'business_cards';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['enterprise_id','integral','deal_amount', 'popularity', 'status','reliable', 'share', 'created_at', 'updated_at','follow','copy_phone','deal_order','see_pro','copy_email','copy_wechat','see_dynamic','see_website','call_phone','autograph_fabulous','information_num','inactive_num','active_num','invitations_num','deal_num','play_voice'], 'integer'],
            [['details'], 'string'],
            [['portrait','address','voice'], 'string', 'max' => 255],
            [['autograph'], 'string', 'max' => 500],
            [['name','userid','corpid','openid', 'tel', 'wechat', 'position', 'company','email'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'enterprise_id' => 'Enterprise ID',
            'userid' => 'userid',
            'corpid' => 'corpid',
            'openid' => 'openid',
            'integral' => 'integral',
            'popularity' => 'Popularity',
            'reliable' => 'Reliable',
            'share' => 'Share',
            'follow' => 'follow',
            'status' => 'Status',
            'voice' => 'voice',
            'portrait' => 'Portrait',
            'name' => 'Name',
            'tel' => 'Tel',
            'wechat' => 'Wechat',
            'deal_order' => 'deal_order',
            'deal_amount' => 'deal_amount',
            'position' => 'Position',
            'play_voice' => 'play_voice',
            'company' => 'Company',
            'email' => 'email',
            'details' => 'Details',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        unset($fields["updated_at"], $fields["created_at"]);
    }

    /**
     * @return string
     * @throws \EasyWeChat\Kernel\Exceptions\InvalidArgumentException
     * 获取名片二维码
     */
    public function getQrcode(){
        $card_id = $this->id;
        $filename = "card_$card_id.png";
        $file_path =  \Yii::$app->basePath . "/web/qrcode";
        if(!file_exists($file_path . "/" . $filename)){
            $result = Entrance::instance($this->enterprise_id)->app_code->get("pages/card/index?card_id=".$card_id);
            $filename = $result->save($file_path, $filename);
//            $config = \Yii::$app->params["qiniu_config"];
//            $qiniu = new Qiniu($config["accessKey"], $config["secretKey"],$config["domain"], $config["bucket"]);
//            $key = date("Ymd")."/".time().".png";
//            $qiniu->uploadByUrl(\Yii::$app->request->hostInfo . "/qrcode/$filename",$key,$config["bucket"]);
//            $url = $qiniu->getImgStyleLink($key,$config["style"]);
//            return $url;
        }
        return \Yii::$app->request->hostInfo . "/qrcode/$filename";
    }

    /**
     * @return string
     * 获取员工头像
     */
    public function getUserAvatar(){
        $enterprise_user = EnterpriseUser::findOne(["userid" => $this->userid , "corpid" => $this->corpid]);
        if(!empty($enterprise_user)){
            return $enterprise_user->avatar;
        }
    }




}
