<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/1
 * Time: 17:16
 */
namespace api\models\pay;

use common\wx_service\Pay;

/**
 * Class MiniProgramPay
 * @package api\models\pay
 */
class MiniProgramPay extends Pay {

    public function __construct($business_id, array $config = [])
    {
        parent::__construct($business_id, $config);
    }


    public function getPayConfig()
    {
        return parent::getPayConfig(); // TODO: Change the autogenerated stub
    }


    public function unify(array $order)
    {
        return parent::unify($order); // TODO: Change the autogenerated stub
    }


    static public function getInstance($business_id, $config = [])
    {
        return parent::getInstance($business_id, $config); // TODO: Change the autogenerated stub
    }


    public function getJsSdk()
    {
        return parent::getJsSdk(); // TODO: Change the autogenerated stub
    }
}



