<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/23
 * Time: 17:36
 */
namespace api\controllers;

class HandleController extends IndexController{

    /**
     * @param $action
     * @return bool
     * @throws \Exception
     * @throws \yii\web\BadRequestHttpException
     * 方法调用前验证token的有效性
     */
    public function beforeAction($action){
        if(!$this->actionCheck()){
            throw new \Exception('Token does not exist or invalid');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}