<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/5
 * Time: 13:51
 */
namespace api\modules\staff\controllers;

use api\modules\staff\logic\Customer;
use common\models\card\BusinessCardsRecords;
use common\models\common\FollowStatus;
use common\models\customer\FollowTask;
use yii\rest\Controller;

class CustomerController extends Controller{

    public $modelClass = '';

    public $card_id;

    /**
     * @var Customer
     */
    public $customer;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(!\Yii::$app->request->isPost){
            return ["code"=>400,"message"=>"请求方式错误"];
        }
        //todo card_id 的获取路径待处理
        $this->card_id = \api\models\get_card_id();
        if(empty($this->card_id) || !is_numeric($this->card_id)){
            return ["code" => 400 ,"message" => "请求参数错误"];
        }
        $this->customer = new Customer($this->card_id);
    }

    /**
     * @return array
     * 雷达
     */
    public function actionRadar(){
        $record_id = \Yii::$app->request->post("record_id");
        if(empty($record_id) || !is_numeric($record_id)){
            return ["code"=>400,"message"=>"请求参数错误"];
        }
        $card_record = $this->customer->getCardRecord($record_id);
        if(empty($card_record)){
            return ["code"=>404,"message"=>"客户不存在"];
        }
        $screen = FollowStatus::labels();
        return [
            "code" => 200,
            "data" => [
                "customer_info" => $card_record,
                "task" => $this->customer->getTask($record_id),
                "screen" => $screen
            ]
        ];
    }


    /**
     * @return array
     * 操作记录
     */
    public function actionRecord(){
        $record_id = \Yii::$app->request->post("record_id");
        if(empty($record_id) || !is_numeric($record_id)){
            return ["code"=>400,"message"=>"请求参数错误"];
        }
        $card_record = $this->customer->getCardRecord($record_id);
        if(empty($card_record)){
            return ["code"=>404,"message"=>"客户不存在"];
        }
        return [
            "code" => 200,
            "data" => $this->customer->getOperationRecord($record_id)
        ];
    }


    /**
     * @return array
     * 添加任务
     */
    public function actionAddTask(){
        $record_id = \Yii::$app->request->post("record_id");
        if(empty($record_id) || !is_numeric($record_id)){
            return ["code"=>400,"message"=>"请求参数错误"];
        }
        $card_record = $this->customer->getCardRecord($record_id);
        if(empty($card_record)){
            return ["code"=>404,"message"=>"客户不存在"];
        }
        $name = \Yii::$app->request->post("name");
        $back_time = \Yii::$app->request->post("back_time");
        $back_time = strtotime($back_time);
        if(empty(trim($name))){
            return ["code"=>400,"message"=>"请填写任务名称"];
        }
        if(empty($back_time)){
            return ["code"=>400,"message"=>"请选择时间"];
        }
        $follow_task = new FollowTask();
        $follow_task->name = $name;
        $follow_task->enterprise_id = $card_record["enterprise_id"];
        $follow_task->record_id = $record_id;
        $follow_task->card_id = $this->card_id;
        $follow_task->back_time = $back_time;
        $follow_task->created_at = time();
        $follow_task->updated_at = time();
        if($follow_task->save()){
            return ["code"=>200,"message"=>"任务添加成功"];
        }
        return ["code"=>400,"message"=>"任务添加失败"];
    }


    /**
     * @return array
     * 获取用户的兴趣
     */
    public function actionInterestChart(){
        $record_id = \Yii::$app->request->post("record_id");
        if(empty($record_id) || !is_numeric($record_id)){
            return ["code"=>400,"message"=>"请求参数错误"];
        }
        $card_record = $this->customer->getCardRecord($record_id);
        if(empty($card_record)){
            return ["code"=>404,"message"=>"客户不存在"];
        }
        $result  = $this->customer->getInterestChart($record_id);
        list($interest , $interaction) = $result;
        return [
            "code"=>200,
            "data"=>[
                "interest"=> $interest,
                "interaction" => $interaction
            ] ,
            "message"=>"请求成功"
        ];
    }

    /**
     * @return array
     * 更改跟进状态
     */
    public function actionUpdateStatus(){
        $record_id = \Yii::$app->request->post("record_id");
        $follow_status = \Yii::$app->request->post("follow_status");
        if(empty($record_id) || !isset($follow_status)){
            return ["code" => 400, "message" => "请求参数错误"];
        }
        $result = $this->customer->updateStatus($record_id,$follow_status);
        if($result){
            return ["code" => 200 ,"message" => "修改成功"];
        }
        return ["code" => 400 , "message" => "修改失败"];
    }


}