<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/28
 * Time: 21:20
 */
namespace api\modules\staff\controllers;

use api\modules\staff\logic\Index;
use common\helper\Common;
use common\models\card\BusinessCards;
use common\models\common\ActivityStatus;
use common\models\common\FollowStatus;
use common\models\dynamic\EnterpriseDynamic;
use common\models\dynamic\EnterpriseDynamicFabulous;
use yii\rest\ActiveController;

class IndexController extends ActiveController {

    public $modelClass = '';

    public $card_id;

    /**
     * @var Index
     */
    public $index_logic;

    public function init(){
        parent::init(); // TODO: Change the autogenerated stub
        if(!\Yii::$app->request->isPost){
            return ["code"=>400,"message"=>"请求方式错误"];
        }
        $this->card_id = \api\models\get_card_id();
        $this->index_logic = new Index($this->card_id);
    }

    /**
     * @return array
     * 获取名片信息详情
     */
    public function actionCard(){
        $card = BusinessCards::findOne($this->card_id);
        if(empty($card)){
            return ["code" => 400 , "message" => "名片不存在"];
        }
        return ["code" => 200 , "data" => $card->getAttributes(["id","popularity","reliable","share","voice","address","autograph","portrait","name","tel","autograph","autograph_fabulous","wechat","position","company","email","details"]), "message" => "请求成功"];
    }

    /**
     * @return array
     * 个人名片编辑
     */
    public function actionEdit(){
        if(empty($this->card_id)){
            return ["code" => 400, "message"=>"参数请求错误"];
        }
        $card = BusinessCards::findOne($this->card_id);
        if(empty($card) || $card->status != ActivityStatus::STATUS_NORMAL){
            return ["code"=> 400 , "message" => "名片不存在或则已删除"];
        }
        $post = \Yii::$app->request->post();
        $card->setAttributes([
            "portrait" => !empty($post["portrait"]) ? $post["portrait"] : "",
            "name" => !empty($post["name"]) ? $post["name"] : "",
            "tel" => !empty($post["tel"]) ? $post["tel"] : "",
            "wechat" => !empty($post["wechat"]) ? $post["wechat"] : "",
            "position" => !empty($post["position"])? $post["position"] : "",
            "company" => !empty($post["company"])? $post["company"] : "",
            "email" => !empty($post["email"])? $post["email"] : "",
            "autograph" => !empty($post["autograph"])? $post["autograph"] : "",
            "address" => !empty($post["address"])? $post["address"] : "",
            "voice" => !empty($post["voice"])? $post["voice"] : ""
        ]);
        if($card->save()){
            return ["code" => 200,  "message" => "修改成功"];
        }
        return ["code" => 400 , "message" => "修改失败" ];
    }


    /**
     * @return array
     * 统计
     */
    public function actionStatistics(){
        $time_between = \Yii::$app->request->post("time_between");
        if(empty($this->card_id) || !is_numeric($this->card_id)){
            return ["code" => 400 , "message" => "参数错误"];
        }
        return ["code" => 200 ,"data" => $this->index_logic->me($time_between) , "message" => "请求成功"];
    }


    /**
     * @return array
     * 我的今日数据 图表
     */
    public function actionChart(){
        $time_between = \Yii::$app->request->post("time_between");
        if(empty($this->card_id) || !is_numeric($this->card_id)){
            return ["code" => 400 , "message" => "参数错误"];
        }
        list($interest , $interaction) = $this->index_logic->getInterest($time_between);
        return ["code" => 200 ,"data" => [
            "latticeData" => $this->index_logic->getLatticeData($time_between),
            "interest" => $interest,
            "interaction" => $interaction
        ] , "message" => "请求成功"];
    }


    /**
     * @return array
     * 获取我的业绩
     */
    public function actionAchievement(){
        $time_between = \Yii::$app->request->post("time_between");
        if(empty($this->card_id) || !is_numeric($this->card_id)){
            return ["code" => 400 , "message" => "参数错误"];
        }
        return ["code" => 200 ,"data" => Index::getAchievement($time_between , $this->card_id) , "message" => "请求成功"];
    }


    /**
     * @return array
     * 获取我的动态
     */
    public function actionMyDynamic(){
        if(empty($this->card_id) || !is_numeric($this->card_id)){
            return ["code" => 400 , "message" => "参数请求错误"];
        }
        $dynamic = EnterpriseDynamic::find()
            ->where(["card_id" => $this->card_id,"status" => ActivityStatus::STATUS_NORMAL])
            ->with("user")
            ->asArray()
            ->orderBy("created_at desc")
            ->all();
        $data = [];
        foreach ($dynamic as $item => $value){
            $data[$item]["id"] = $value["id"];
            $data[$item]["describe"] = $value["describe"];
            $data[$item]["created_at"] = date("Y/m/d" , $value["created_at"]);
            $data[$item]["name"] = $value["user"]["name"];
        }
        return ["code" => 200 , "data" => $data ,"message" => "数据请求成功"];
    }

    /**
     * @return array
     * 添加动态
     */
    public function actionAddDynamic(){
        if(empty($this->card_id) || !is_numeric($this->card_id)){
            return ["code" => 400 , "message" => "参数请求错误"];
        }
        $describe = \Yii::$app->request->post("describe");
        if(empty($describe)){
            return ["code" => 400 , "message" => "内容不能为空"];
        }
        $img = \Yii::$app->request->post("img" , "");
        $card = BusinessCards::findOne($this->card_id);
        $dynamic = new EnterpriseDynamic();
        $dynamic->enterprise_id = $card->enterprise_id;
        $dynamic->card_id = $card->id;
        $dynamic->img = $img;
        $dynamic->describe = $describe;
        $dynamic->created_at = time();
        $dynamic->updated_at = time();
        if($dynamic->save()){
            return ["code" => 200 , "message" => "发布成功"];
        }
        return ["code" => 500 , "message" => "发布失败"];

    }

    /**
     * @return array
     * 动态删除
     */
    public function actionDynamicDelete(){
        if(empty($this->card_id) || !is_numeric($this->card_id)){
            return ["code" => 400 , "message" => "参数请求错误"];
        }
        $dynamic_id = \Yii::$app->request->post("dynamic_id");
        if(empty($dynamic_id) || !is_numeric($dynamic_id)){
            return ["code" => 400 , "message" => "参数请求错误"];
        }
        $dynamic = EnterpriseDynamic::findOne($dynamic_id);
        if($dynamic->status != ActivityStatus::STATUS_NORMAL){
            return ["code" => 400, "message" => "请勿重新删除"];
        }
        $dynamic->status = ActivityStatus::STATUS_DELETE;
        if($dynamic->save()){
            return ["code" => 200 , "message" => "删除成功"];
        }
        return ["code" => 400 , "message" => "删除失败"];
    }


    /**
     * @return array
     * 获取指定类目操作记录
     */
    public function actionHandleRecord(){
        $place = \Yii::$app->request->post("place");
        $operation_type = \Yii::$app->request->post("operation_type");
        if(empty($this->card_id) || !is_numeric($this->card_id)){
            return ["code" => 400 , "message" => "参数请求错误"];
        }
        return ["code" => 200 , "message" => "请求成功","data" => $this->index_logic->getHandleRecord($operation_type , $place)];
    }










}