<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/11
 * Time: 16:59
 */
namespace api\modules\staff\controllers;

use api\modules\staff\logic\Mail;
use common\models\common\FollowStatus;
use yii\rest\Controller;

class MailController extends Controller{

    public $modelClass = '';

    public $card_id;

    /**
     * @var Mail
     */
    public $mail;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(!\Yii::$app->request->isPost){
            return ["code"=>400,"message"=>"请求方式错误"];
        }
        //todo card_id 的获取路径待处理
        $this->card_id = \api\models\get_card_id();
        if(empty($this->card_id) || !is_numeric($this->card_id)){
            return ["code" => 400 ,"message" => "请求参数错误"];
        }
        $this->mail = new Mail($this->card_id);
    }

    /**
     * @return array
     * 通讯录列表
     */
    public function actionList(){
        list($record, $page) = $this->mail->getList(\Yii::$app->request->post("follow_status") ,\Yii::$app->request->post("search_key"));
        $screen = FollowStatus::labels();
        $screen[-1] = "全部";
        return ["code"=>200,"data"=>[
            "record" => $record ,
            "screen" => $screen,
            "page"  => $page
        ],"message"=>"请求成功"];
    }

    /**
     * @return array
     * 添加客户
     */
    public function actionAddCustomer(){
        $name = \Yii::$app->request->post("name","");
        $phone = \Yii::$app->request->post("phone","");
        $wechat = \Yii::$app->request->post("wechat","");
        $card_id = $this->card_id;
        $result = $this->mail->addCustomer([
            "card_id" => $card_id,
            "phone" => $phone,
            "name"  => $name,
            "wechat" =>  $wechat
        ]);
        if($result){
            return ["code" => 200 , "message" => "添加成功"];
        }
        return ["code" => 400 , "message" => "添加失败"];
    }



}